import Link from 'next/link';

export default function AboutPage() {
  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="px-6 py-4 border-b border-[#E0E0E0]">
        <Link href="/" className="text-heading hover:text-[#E65100]">
          TV Ratings
        </Link>
      </header>

      {/* Main Content */}
      <main className="flex-1 px-6 py-8">
        <div className="max-w-xl mx-auto">
          <h1 className="text-title mb-8">About</h1>

          <div className="space-y-8">
            <section>
              <h2 className="text-micro text-[#757575] mb-3">What is this</h2>
              <p className="text-body leading-relaxed">
                TV Ratings analyzes movies and TV shows from different ideological
                perspectives using AI. It searches the web and compiles information,
                presenting it through your chosen viewpoint.
              </p>
            </section>

            <div className="divider" />

            <section>
              <h2 className="text-micro text-[#757575] mb-3">Disclaimer</h2>
              <div className="card p-6">
                <p className="text-body leading-relaxed">
                  All analyses are generated by artificial intelligence. Content is
                  automatically produced and may contain inaccuracies or biases.
                </p>
                <p className="text-body leading-relaxed mt-4">
                  The author does not bear responsibility for the accuracy or
                  implications of AI-generated content. Analyses do not represent
                  personal views of the creator.
                </p>
              </div>
            </section>

            <div className="divider" />

            <section>
              <h2 className="text-micro text-[#757575] mb-3">How it works</h2>
              <p className="text-body leading-relaxed">
                Submit a title and select a perspective level (0 = progressive,
                10 = traditional). The AI searches the web for information about
                the content, then analyzes it from your chosen viewpoint.
              </p>
            </section>

            <div className="divider" />

            <section>
              <h2 className="text-micro text-[#757575] mb-3">Purpose</h2>
              <p className="text-body leading-relaxed">
                This tool demonstrates how the same media can be perceived differently
                depending on ideological viewpoint. It is for entertainment and
                educational purposes only.
              </p>
            </section>
          </div>

          <div className="mt-12 pt-8 border-t border-[#E0E0E0]">
            <Link href="/" className="text-caption text-[#757575] hover:text-[#E65100]">
              Back
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
