import Link from 'next/link';

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-black flex flex-col">
      {/* Header */}
      <header className="border-b border-gray-800 px-4 py-3">
        <Link href="/" className="text-lg font-bold uppercase tracking-wider text-green-500 hover:text-green-400">
          TV Ratings
        </Link>
      </header>

      {/* Main Content */}
      <main className="flex-1 p-4 pt-6 max-w-2xl mx-auto">
        <h1 className="text-2xl font-bold text-white mb-6">About TV Ratings</h1>

        <div className="space-y-6 text-gray-300 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">What is this?</h2>
            <p>
              TV Ratings is an experimental tool that analyzes movies and TV shows from different
              ideological perspectives. It uses AI to search the web and compile information about
              media content, then presents that information through the lens of your chosen perspective.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">AI Disclaimer</h2>
            <div className="bg-yellow-900/20 border border-yellow-800/50 rounded-lg p-4">
              <p className="text-yellow-200/80">
                All analyses on this site are generated by artificial intelligence (Claude by Anthropic).
                The content is automatically produced and may contain inaccuracies, biases, or errors.
              </p>
              <p className="mt-3 text-yellow-200/80">
                The author of this website does not bear any responsibility for the accuracy, completeness,
                or implications of the AI-generated content. The analyses do not represent the personal
                views or opinions of the website creator.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">How it works</h2>
            <p>
              When you submit a title, the AI searches the web for information about the movie or TV show,
              including plot details, reviews, and any cultural discourse surrounding it. It then analyzes
              this information from the perspective level you selected (0 = progressive, 10 = conservative)
              and generates a rating with supporting details.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">Intended use</h2>
            <p>
              This tool is meant for entertainment and educational purposes only. It demonstrates how the
              same media can be perceived differently depending on one&apos;s ideological viewpoint. It is not
              meant to promote any particular political ideology or to serve as a definitive guide for
              content decisions.
            </p>
          </section>
        </div>

        <div className="mt-8 pt-6 border-t border-gray-800">
          <Link href="/" className="text-green-500 hover:text-green-400 text-sm">
            &larr; Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}
